FROM python:3.10-slim

WORKDIR /recall

COPY requirements.txt .

# Install runtime dependencies only
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    netcat-openbsd \
    gcc \
    g++ \
    portaudio19-dev \
    libasound2-dev \
    tesseract-ocr \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/* 

# Install Python dependencies
RUN pip install -r requirements.txt


# Copy application code
COPY . .
WORKDIR /recall

# Run the application
CMD ["python", "/recall/src/mss_screen.py"]