version: '3.8'

services:
    qdrant:
        image: qdrant/qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - ./data-qdrant:/qdrant/storage

    recall:
        build:
            context: .
            dockerfile: Dockerfile.recall
        volumes:
            - C:/RecallAI/images_taken:/recall_ai/images_taken
            - .:/recall
        ports:
            - "8005:8005"
        depends_on:
            - qdrant
        env_file:
            - .env
        command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8005"]

    faiss-store:
        build:
            context: .
            dockerfile: Dockerfile.Faiss.db
        env_file:
            - .env
        volumes:
            - C:/RecallAI/images_taken:/recall_ai/images_taken
        command: ["python", "recall_ai/config/gen_vector_embedding.py"]

    quadrant-store:
        build:
            context: .
            dockerfile: Dockerfile.Quad.db
        depends_on:
            - qdrant
        env_file:
            - .env
        volumes:
            - C:/RecallAI/images_taken:/recall_ai/images_taken
        command: ["python", "recall_ai/config/quad_gen_vector_embedding.py"]
