FROM python:3.10-slim

WORKDIR /recall

COPY requirements.txt .

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    netcat-openbsd \
    pkg-config \
    gcc \
    g++ \
    portaudio19-dev \
    libasound2-dev \
    tesseract-ocr \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/* 

RUN pip install -r requirements.txt

# Copy application code
COPY . .

RUN chmod +x waitforkafka.sh


# Default CMD just runs the Kafka config (compose will override this with wait script + Python)
CMD ["python", "/recall_ai/config/quad_gen_vector_embedding.py"]